export const BID_LIST_REQUEST = 'BID_LIST_REQUEST';
export const BID_LIST_SUCCESS = 'BID_LIST_SUCCESS';
export const BID_LIST_FAIL = 'BID_LIST_FAIL';

export const BID_DETAILS_REQUEST = 'BID_DETAILS_REQUEST';
export const BID_DETAILS_SUCCESS = 'BID_DETAILS_SUCCESS';
export const BID_DETAILS_FAIL = 'BID_DETAILS_FAIL';


export const BID_CREATE_REQUEST = 'BID_CREATE_REQUEST';
export const BID_CREATE_SUCCESS = 'BID_CREATE_SUCCESS';
export const BID_CREATE_FAIL = 'BID_CREATE_FAIL';

export const BID_EDIT_REQUEST = 'BID_EDIT_REQUEST';
export const BID_EDIT_SUCCESS = 'BID_EDIT_SUCCESS';
export const BID_EDIT_FAIL = 'BID_EDIT_FAIL';
export const BID_EDIT_RESET = 'BID_EDIT_RESET';