export const BID_LIST_REQUEST = "BID_LIST_REQUEST";
export const BID_LIST_SUCCESS = "BID_LIST_SUCCESS";
export const BID_LIST_FAIL = "BID_LIST_FAIL";

export const BID_DETAILS_REQUEST = "BID_DETAILS_REQUEST";
export const BID_DETAILS_SUCCESS = "BID_DETAILS_SUCCESS";
export const BID_DETAILS_FAIL = "BID_DETAILS_FAIL";

export const BID_CREATE_REQUEST = "BID_CREATE_REQUEST";
export const BID_CREATE_SUCCESS = "BID_CREATE_SUCCESS";
export const BID_CREATE_FAIL = "BID_CREATE_FAIL";

export const BID_ACCEPT_REQUEST = "BID_ACCEPT_REQUEST";
export const BID_ACCEPT_SUCCESS = "BID_ACCEPT_SUCCESS";
export const BID_ACCEPT_FAIL = "BID_ACCEPT_FAIL";
export const BID_ACCEPT_RESET = "BID_ACCEPT_RESET";

export const BID_DECLINE_REQUEST = "BID_DECLINE_REQUEST";
export const BID_DECLINE_SUCCESS = "BID_DECLINE_SUCCESS";
export const BID_DECLINE_FAIL = "BID_DECLINE_FAIL";
export const BID_DECLINE_RESET = "BID_DECLINE_RESET";

export const BID_MADE_LIST_REQUEST = "BID_MADE_LIST_REQUEST";
export const BID_MADE_LIST_SUCCESS = "BID_MADE_LIST_SUCCESS";
export const BID_MADE_LIST_FAIL = "BID_MADE_LIST_FAIL";
export const BID_MADE_LIST_RESET = "BID_MADE_LIST_RESET";

export const JOB_COMPLETED_REQUEST = "JOB_COMPLETED_REQUEST";
export const JOB_COMPLETED_SUCCESS = "JOB_COMPLETED_SUCCESS";
export const JOB_COMPLETED_FAIL = "JOB_COMPLETED_FAIL";
export const JOB_COMPLETED_RESET = "JOB_COMPLETED_RESET";
